# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ricky Han blog
email: "rickyhan+blog@rickyhan.com"
description: >
  Programming demos, tips, thoughts
baseurl: ""
url: "http://rickyhan.com"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
highlighter: rouge
